### ISSUE TITLE
How to use the model predictions to select the samples

### ISSUE THREAD

**Issue by AhmadShaik** [jacobmarks/active-learning-plugin#3]
@jacobmarks - I became your fan after looking at your work. Great work. 

I am trying to use the active learning pipeline for a classification problem. Based on the blog, I understood that currently 51 active learning plugin can provide a fecility to select various ML based algorithms to train, predict and select the samples based on the embeddings. 

But I need to use the ground truth labels and custom model prections (class names and confidence) to select the samples. Can you tell me how it can be done with the existing plugin.

**Comment by jacobmarks** [comment]
Hey @AhmadShaik , glad to hear you found the blog post useful :) 

Your understanding is correct: this plugin allows you to streamline the process of labeling your data. I would suggest combining this with the [zero-shot prediction plugin](https://github.com/jacobmarks/zero-shot-prediction-plugin) to generate initial labels for your dataset, and then doing active learning from there.

To compute embeddings, in Python you can run:

```py
import fiftyone as fo
import fiftyone.zoo as foz

## load an example dataset
dataset = foz.load_zoo_dataset("quickstart")

## load model to compute embeddings with
model = foz.load_zoo_model("clip-vit-base32-torch")

## compute embeddings
dataset.compute_embeddings(model, embeddings_field = "clip_embeddings")
```

Closing this for now :)
